services:
  client:
    build:
      context: ./client/
      target: developement
    volumes:
      - ./client:/code
    ports:
      - 40498:40498
    depends_on:
      - server
    env_file:
      - ./client/.dev.env

  server:
    build:
      context: ./server/
      target: developement
    volumes:
      - ./server:/code
    ports:
      - 30498:30498
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - ./data/db:/data/db
    command: mongod --quiet --logpath /dev/null
